### ISSUE TITLE
p2dfmt -> gmsh

### ISSUE THREAD

**Issue by vhuber** [mrklein/p3d2gmsh#1]
Hi there,

I just receive a c++ code from Martin Vymazal to convert the 2D version of the flates plates (from the nasa web site) to gmsh files.

He gave me permission to distribute that code.
Are you interested in hosting in that specific code on this repo ?

All the best,

VH.

**Comment by mrklein** [comment]
Hi,

Thank you for proposal. Does the code converts mesh only for flatplate case or it is more universal? Any way we can try to use standard procedure: fork -> add code -> commit -> pull request.

**Comment by vhuber** [comment]
The code has been written only for the 2D flateplate p2dfmt from the nasa.
Thus it is not universal, but can be a good starting point for someone that need an universal code.

I'm not very confident with the procedure, I'll work on it those days.

**Comment by woensug-choi** [comment]
Could you share the 2D code?? I am trying to replicate the 2D flatplate problem. Thx in advance.
kickflipin@snu.ac.kr

**Comment by vhuber** [comment]
@kickflipin Please have a look [here](https://github.com/vhuber/p3d2gmsh)
