### ISSUE TITLE
Converting Construct2D generated meshes

### ISSUE THREAD

**Issue by Cirdans-Home** [mrklein/p3d2gmsh#3]
Hi,

I'm trying to convert some p3d meshes generated by the Construct2D code ([https://sourceforge.net/projects/construct2d/](https://sourceforge.net/projects/construct2d/))  up with a GMSH file of a different mesh.

As an example, I generate the mesh for the naca0012 airfoil, then:
./p3d2gmsh.py -o naca0012.msh -m naca0012.nmf naca0012.p3d

Then starting from this mesh:
![naca0012original](https://user-images.githubusercontent.com/1467455/40482102-dcea0960-5f53-11e8-8076-cdd9c2a20ac9.png)
I end up with the following one:
![naca0012](https://user-images.githubusercontent.com/1467455/40482016-8d699e6e-5f53-11e8-9efc-73ff7696424f.png)

These are both the original p3d file, the map and the mesh converted in gmsh format. [naca_mesh_conversion.tar.gz](https://github.com/mrklein/p3d2gmsh/files/2035022/naca_mesh_conversion.tar.gz)

Best Regards,

**Comment by mrklein** [comment]
Hi,

Your files do have the problem. Yet, they are a little bit strange, your p3d file looks like 2D. You can compare them with n0012.* files in tests folder of the repository.

If we assume, that P3D output format has been a little bit changed between Construct2D versions, could you specify version you have used to generate the mesh?

**Comment by Cirdans-Home** [comment]
Hi,

I'm using version Construct2D Version 2.1.4 and I'm using it to generate 2D structured grid so I think that the p3d file should indeed look like a 2D file (without the number of points/elements in the 3rd direction).

Thank you very much for your assistance.

**Comment by mrklein** [comment]
I have checked Construct2D 2.1.4 output and it turns out, you do try to convert 2D grid files.

Script expects 3D grid files. Since I have written it to utilise with OpenFOAM, I did not implement conversion of 2D files, since it was unnecessary extra-functionality.

**Comment by Cirdans-Home** [comment]
Thanks anyway, I'll try to figure out if I can change the code to add this feature.
