### ISSUE TITLE
naca mesh does not show in gmsh

### ISSUE THREAD

**Issue by cpraveen** [mrklein/p3d2gmsh#4]
When I open the included naca msh file in latest gmsh, no mesh is displayed. I also dont get any error in gmsh. Do you know what could be wrong ?

**Comment by mrklein** [comment]
By default new versions of Gmsh read mesh files version 4.0, one in the repository in version 2.0 (and script generates MSH files version 2.0). I do not plan to update the script but rather implement more universal mesh conversion utility.

**Comment by cpraveen** [comment]
By default, gmsh generates file in latest version. But msh version is present in msh file and gmsh is backward compatible and can read older versions. Strangely it does not give any error also.

**Comment by cpraveen** [comment]
Please see this also http://onelab.info/pipermail/gmsh/2018/012618.html

**Comment by cpraveen** [comment]
Copying 4th column value into 5th column (instead of -1) will fix this issue. I have attached a patch file.
[tag.patch.txt](https://github.com/mrklein/p3d2gmsh/files/2568203/tag.patch.txt)
